const languageMap: { [key: string]: string } = {
	en: 'Inglês',
	es: 'Espanhol',
	fr: 'Francês',
	de: 'Alemão',
	it: 'Italiano',
	pt: 'Português',
	ru: 'Russo',
	ja: 'Japonês',
	zh: 'Chinês',
	ko: 'Coreano',
	hi: 'Hindi',
	ar: 'Árabe',
	nl: 'Holandês',
	sv: 'Sueco',
	no: 'Norueguês',
	da: 'Dinamarquês',
	fi: 'Finlandês',
	el: 'Grego',
	he: 'Hebraico',
	hu: 'Húngaro',
	pl: 'Polonês',
	ro: 'Romeno',
	th: 'Tailandês',
	tr: 'Turco',
	uk: 'Ucraniano',
	vi: 'Vietnamita',
	cs: 'Checo',
	sk: 'Eslovaco',
	sl: 'Esloveno',
	bg: 'Búlgaro',
	hr: 'Croata',
	sr: 'Sérvio',
	lt: 'Lituano',
	lv: 'Letão',
	et: 'Estoniano',
	ms: 'Malaio',
	id: 'Indonésio',
	fa: 'Persa',
	bn: 'Bengali',
	ta: 'Tâmil',
	te: 'Telugu',
	mr: 'Marathi',
	sw: 'Swahili',
	af: 'Africâner',
	eu: 'Bascão',
	gl: 'Galego',
	ca: 'Catalão',
	is: 'Islandês',
	ga: 'Irlandês',
	mk: 'Macedônio'
}

export function getLanguageFullName(languageCode: string): string {
	return languageMap[languageCode] || 'Idioma desconhecido'
}
