import { Footer } from '@/components/footer'
import { Header } from '@/components/header'
import '@/styles/globals.css'
import type { Metadata } from 'next'
import { ViewTransitions } from 'next-view-transitions'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<ViewTransitions>
			<html lang="pt-BR">
				<body className={inter.className}>
					<Header />
					<main className="flex-1 pb-8">{children}</main>
					<Footer />
				</body>
			</html>
		</ViewTransitions>
	)
}
